const mongoose = require("mongoose");

const graduatedStudentSchema = new mongoose.Schema(
  {
    name: { type: String },
    rollNumber: { type: String },
    house: { type: String },
    contactNumber: { type: String },
    admissionNo: { type: String },
    aadhaar: { type: String },
    gender: { type: String },
    religion: { type: String },
    address: { type: String },
    route: { type: String },
    caste: { type: String },
    bloodGroup: { type: String },
    selectedDocumentation: { type: String },
    fathersName: { type: String },
    mothersName: { type: String },
    fathersNo: { type: String },
    mothersNo: { type: String },
    fathersOccupation: { type: String },
    mothersOccupation: { type: String },
    previousSchoolName: { type: String },
    previousSchoolAffiliatedWith: { type: String },
    registrationNumber: { type: String },
    lastExamGiven: { type: String },
    lastExamYear: { type: String },
    lastExamMarks: { type: String },
    lastExamResult: { type: String },
    nameOfLocalGuardian: { type: String },
    addressOfLocalGuardian: { type: String },
    studentSection: { type: String },
    cityVillage: { type: String },
    fathersQualification: { type: String },
    fathersDob: { type: String },
    mothersQualification: { type: String },
    mothersDob: { type: String },
    numberOfLocalGuardian: { type: String },
    dob: { type: String },
    admissionDate: { type: String },
    phoneForSchoolSMS: { type: String },
    transportFacility: { type: String },
    studentClass: { type: String },
    studentAvatar: { public_id: String, secure_url: String },
    fatherPhoto: { public_id: String, secure_url: String },
    motherPhoto: { public_id: String, secure_url: String },
    feeCategory: { type: String },
    graduatedYear: { type: String },
  },
  { timestamps: true }
);

module.exports = mongoose.models.GraduatedStudent || mongoose.model("GraduatedStudent", graduatedStudentSchema);
